# Generated by Django 3.0.7 on 2021-02-17 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 17, 17, 7, 10, 714202, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='posturerecord',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 17, 17, 7, 10, 715230, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sittingrecord',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 17, 17, 7, 10, 715230, tzinfo=utc), null=True),
        ),
    ]
