# Generated by Django 3.0.7 on 2021-02-17 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20210217_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 17, 17, 15, 1, 903908, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='posturerecord',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 17, 17, 15, 1, 904901, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sittingrecord',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 17, 17, 15, 1, 904901, tzinfo=utc), null=True),
        ),
    ]
