# Generated by Django 3.0.7 on 2021-03-04 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20210217_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='github',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='instagram',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='twitter',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 4, 21, 30, 41, 956721, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='posturerecord',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 4, 21, 30, 41, 956721, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sittingrecord',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 4, 21, 30, 41, 956721, tzinfo=utc), null=True),
        ),
    ]
