# Generated by Django 3.0.7 on 2021-03-30 20:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_auto_20210310_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='profile1.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='posturerecord',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 30, 20, 15, 37, 847070, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='posturerecord',
            name='posture_value',
            field=models.CharField(choices=[('1', 'Correct Posture'), ('0', 'Incorrect Posture')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sittingrecord',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 30, 20, 15, 37, 848067, tzinfo=utc), null=True),
        ),
    ]
