# Generated by Django 3.0.7 on 2021-03-30 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_auto_20210330_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posturerecord',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 30, 20, 17, 39, 979803, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='posturerecord',
            name='posture_value',
            field=models.IntegerField(choices=[(1, 'Correct Posture'), (0, 'Incorrect Posture')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sittingrecord',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 30, 20, 17, 39, 980802, tzinfo=utc), null=True),
        ),
    ]
