# Generated by Django 3.0.7 on 2021-04-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_auto_20210401_1615'),
        ('Customer', '0011_auto_20210330_1617'),
    ]

    operations = [
    ]
