# Generated by Django 2.2.5 on 2021-04-20 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_merge_20210417_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posturerecord',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 20, 21, 30, 55, 903274, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sittingrecord',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 20, 21, 30, 55, 904270, tzinfo=utc), null=True),
        ),
    ]
