# -*- coding: utf-8 -*-
"""loadSKlearnModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MAUpS9XwD_mn7Aj91b_pcfn0zDw9HQqr
"""

import pickle
filename = 'model.sav'
#pickle.dump(model, open(filename, 'wb'))
model = pickle.load(open(filename, 'rb'))