# -*- coding: utf-8 -*-
"""loadNumpyData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MAUpS9XwD_mn7Aj91b_pcfn0zDw9HQqr
"""

#save('data.npy', data)
data = load('data.npy')