# -*- coding: utf-8 -*-
"""loadpytorchModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MAUpS9XwD_mn7Aj91b_pcfn0zDw9HQqr
"""

import torch
torch.save(resnet,"./resnet");
resnet = torch.load("./resnet")